name: track_mitra
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  csv: ^5.0.2
  file_picker: ^5.3.0
  flowder: ^0.2.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.6
  open_file_plus: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
